### ISSUE TITLE
labgrid prints debug output in pytest without activation

### ISSUE THREAD

**Issue by SmithChart** [labgrid-project/labgrid#220] opened 2018-03-18 20:08 UTC
I am running pytests using a custom smallubootstrategy inside my project.

When I run pytest using
`pytest  --lg-env local.yaml test_uboot_strategy.py`
I get a lot of debug output from the Serial Output:
`DEBUG: Read 12 bytes: b'0x80000000\r\n', timeout 11.17, requested size 1`
`  DEBUG: Read 11 bytes: b'Loading: *\x08', timeout 11.17, requested size 1`

Since I have neither touched `logging.Logger.setLevel()` nor have used a `-v` on my command line I would just expect some pytest output.

I am currently using latest master + my PullRequests that have not been meged by now.

Is this intended behavior? Or do you have any idea how to track that bug down?

**Comment by jluebbe** [comment] 2018-03-19 15:58
No, that's not intended and I don't see any obvious recent change which would have caused this. Could you try a bisect?

**Comment by Emantor** [comment] 2018-03-29 07:03
Hm, I could not reproduce this behaviour on a quick test with a local Riotboard and current master.
Can you post your test files?

**Comment by Emantor** [comment] 2019-03-22 09:34
Is this still an issue?

**Comment by Emantor** [comment] 2019-05-24 06:27
Closing this, could not reproduce.

**Closed by Emantor** 2019-05-24 06:27 UTC
Labels: bug
