### ISSUE TITLE
Sshpass asks for password after SSHDriver deactivation/reactivation

### ISSUE THREAD

**Issue by githubchriste** [labgrid-project/labgrid#643] opened 2020-10-12 07:37 UTC
I use SshDriver to connect to a target and execute a bunch of commands. The authentication is done with password, not with keyfile.
Sometimes, I need to restart the target and so, the connection to it lost. After it reboots, I try to reconnect to it, by deactivating and reactivating the SSHDriver. 
However, after reactivating the driver, the user password is required to be entered on the command line.
The target has static IP.

**Comment by Emantor** [comment] 2020-10-12 09:30
This is probably a duplicate of #641. I have not had the time to reproduce this yet.

**Comment by Emantor** [comment] 2021-09-15 14:37
We have since added a retry loop and switched to SSH's own env variable, so this should be fixed, closing.

**Closed by Emantor** 2021-09-15 14:37 UTC
Labels: bug, duplicate
