### ISSUE TITLE
Quickstart fails on first step

### ISSUE THREAD

**Issue by Farom** [labgrid-project/labgrid#129] opened 2017-09-11 10:20 UTC
```
~/new$ virtualenv -p python3 labgrid-venv
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in labgrid-venv/bin/python3
Also creating executable in labgrid-venv/bin/python
Failed to import the site module
Traceback (most recent call last):
  File "/home/bla/new/labgrid-venv/lib/python3.5/site.py", line 67, in <module>
    import os
  File "/home/bla/new/labgrid-venv/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
ImportError: No module named '_collections_abc'
ERROR: The executable labgrid-venv/bin/python3 is not functioning
ERROR: It thinks sys.prefix is '/home/bla/new' (should be '/home/bla/new/labgrid-venv')
ERROR: virtualenv is not compatible with this system or executable
~/new$ python3.5 --version
Python 3.5.3
```

**Comment by jluebbe** [comment] 2017-09-11 13:09
Your virtualenv seems to be broken: lib/python3.5/os.py can't import the internal _collections_abc module. The error lines give some more details on what's going wrong.

Closing because it is not caused by labgrid.

**Closed by jluebbe** 2017-09-11 13:09 UTC

**Comment by Farom** [comment] 2017-09-12 09:03
You are right. On a newly created user it works as expected. Thanks.
