### ISSUE TITLE
WARNING: session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session before]

### ISSUE THREAD

**Issue by kjeldflarup** [labgrid-project/labgrid#293] opened 2018-08-07 06:24 UTC
I used to get this error in a python script I wrote, which polled the coordinator until a place was available. The error was then, that I started a new session for every poll. When I started to reuse the session it got stable.

Now I see the error on this command.

```
$ labgrid-client who |  awk /`hostname`/'{printf("labgrid-client -p %s release\n",$3)}' | sh
CRITICAL: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 686, in onMessage
    raise ProtocolError("EVENT received for non-subscribed subscription ID {0}".format(msg.subscription))
autobahn.wamp.exception.ProtocolError: EVENT received for non-subscribed subscription ID 85945492673200

WARNING: dropping connection to peer tcp:10.0.0.84:20408 with abort=True: I dropped the WebSocket TCP connection: WAMP Protocol Error (EVENT received for non-subscribed subscription ID 85945492673200)
WARNING: session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session before]
   INFO: Cancelling 1 outstanding requests
Traceback (most recent call last):
  File "/opt/labgrid/labgrid/remote/client.py", line 1220, in main
    session.loop.run_until_complete(args.func(session))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/opt/labgrid/labgrid/remote/client.py", line 492, in release
    'org.labgrid.coordinator.release_place', place.name
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.close.transport_lost>, args=['WAMP transport was lost without closing the session before'], kwargs={}, enc_algo=None)
```
Both labgrid-client and coordinator is running in containers on the same server, thus network errors are very unlikely.
Could it be some racing condition in the crossbar communication.

**Comment by liaoxuegithup** [comment] 2018-09-17 11:50
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<wamp.close.transport_lost>, args=['WAMP transport was lost without closing the session before'], kwargs={}, enc_algo=None)

**Comment by Emantor** [comment] 2019-05-24 06:29
Is this still an issue with recent updates to crossbar and autobahn?

**Comment by spark5** [comment] 2019-07-02 09:15
Even with latest updates on autobahn, I am also receiving this kind of error in my exporter.

I am also polling coordinator until a place is available. The coordinator starts to throw with warnings such as "event is not in store" etc., but it is able to restart itself when it crashes because i have set it as systemctl service, just like the exporter.

However, I saw that coordinator doesn't know the previous state of places after it restarts itself. So all the acquired places are available. Comments or aliases of places are preserved.

**Comment by Emantor** [comment] 2019-07-02 09:20
https://github.com/labgrid-project/labgrid/commit/437efe337e8cae038b1e016b62b64d85ae653e0b removed the event store since it is not used within labgrid. Please adjust your crossbar configuration accordingly and try to reproduce. 

The unlock of all places after a coordinator restart is expected, since the acquired state does not persist between restarts.

**Comment by spark5** [comment] 2019-07-02 09:29
Ok. I will get latest again on labgrid. Thanks!

But acquired state shouldn't it be persistent? It would be nice for labgrid to cope with failures: work after a restart without losing everything.

**Comment by spark5** [comment] 2019-07-12 13:52
With latest on labgrid, after a few days, the coordinator crashed with reason:
[Controller   4825] Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended by signal 7

The last requests in coordinator were for OTG resource from one of my exporters. In that time, one board was running some tests and pytest reported:
WARNING: session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session before]

What could be the problem?

**Comment by spark5** [comment] 2019-07-18 08:57
Hi!

The coordinator crashed again with same message: Native worker connection closed uncleanly: A process has ended with a probable error condition: process ended by signal 7

I don't even understand why is crashing. Can you please help me?

**Comment by Emantor** [comment] 2019-07-18 09:40
For some reason the worker dies and currently crossbar does not start a new worker. Signal 7 looks suspicious, but I have no idea why it crashes.

**Comment by spark5** [comment] 2019-07-18 10:47
How can i enable debugging on coordinator?

**Comment by Emantor** [comment] 2019-07-18 10:52
https://crossbar.io/docs/Logging/ should be the relevant documentation.

**Comment by spark5** [comment] 2019-07-30 07:17
Hi!

After exactly 6 days it happened again: the coordinator crashed.
I have enabled the debug mode in coordinator last time.

So the coordinator as systemctl service was trying to restart itself, but it couldn't do it.
It was stuck at this:
```
Validate 'call_result' for 'org.labgrid.authenticate'
 crossbar.router.router.Router] session "8306532619252289" joined realm "realm1"
 crossbar.router.service.RouterServiceAgent] RouterServiceAgent.publish("wamp.session.on_join") -> "wamp.session.on_join" on "realm1"
 crossbar.router.role.RouterRole] CrossbarRouterRoleStaticAuth.authorize public org.labgrid.coordinator.set_resource call
```

**Comment by spark5** [comment] 2019-07-30 07:24
Some restarts also contain this:
```
RouterServiceAgent.publish("wamp.session.on_leave")
[Router       3407 crossbar.router.router.Router] session "5564984616804524" left realm "realm1"
[Router       3407 crossbar.router.protocol.WampWebSocketServerProtocol] dropping connection to peer
[Router       3407 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:<IP>:34660 was
[Router       3407 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (
[Router       3407 crossbar.router.protocol.WampWebSocketServerProtocol] WAMP-over-WebSocket transport lost: wasClean=Tr
[Router       3407 crossbar.router.protocol.WampWebSocketServerProtocol]
```

I assume it's because the exporters were also trying to connect to coordinator. But I am not sure.
Each exporter is also running as systemctl service.

**Comment by Emantor** [comment] 2020-12-03 11:36
Newer crossbar/autobahn versions are more reliable, I have not observed these errors in a while, closing this issue.

**Closed by Emantor** 2020-12-03 11:36 UTC
